### ISSUE TITLE
Numba celltree crashes due to out-of-bounds array access of statically sized stack  

### ISSUE THREAD

**Issue by smknaake** [Deltares/numba_celltree#22]
Using `xugrid.OverlapRegridder` throws IndexError with mapbox_earcut triangle results from polygons. 

Throws: `IndexError: index 128 is out of bounds for axis 0 with size 128` which is caused by a pre-allocated array.

**Comment by Huite** [comment]
Should be fixed by #23

I did a quick benchmark as in #13, checking size seems to make no noticeable difference; and re-allocations will generally be rare.
